/**
 * Observability module exports.
 */

export { logger, createLogger, LogLevel } from "./logger.js";
export {
  metrics,
  httpRequestsTotal,
  httpRequestDuration,
  httpRequestSize,
  httpResponseSize,
  activeConnections,
  cacheHits,
  cacheMisses,
  feedPollDuration,
  feedErrors,
  feedEntitiesProcessed,
  pushNotificationsSent,
  pushNotificationsFailed,
  pushSubscriptionsActive,
  tripsCreated,
  tripsActive,
  tripsQueried,
  tripQueryDuration,
  commuteAnalysisRequests,
  commuteAnalysisDuration,
  stationSearchRequests,
  stationSearchDuration,
  stationSearchResults,
  delayPredictionRequests,
  delayPredictionDuration,
  delayPredictionAccuracy,
  contextDetections,
  contextTransitions,
  contextOverrides,
  alertsActive,
  alertsMatchRate,
  alertsChanges,
  equipmentOutages,
  equipmentElevatorsOut,
  equipmentEscalatorsOut,
} from "./metrics.js";
export {
  tracer,
  tracingMiddleware,
  tracedFetch,
  withChildSpan,
  recordEvent,
  setSpanAttribute,
  getCurrentTraceId,
} from "./tracing.js";
