export { requestId } from "./request-id.js";
export { rateLimiter } from "./rate-limiter.js";
export {
  securityHeaders,
  generateCspNonce,
  getDefaultCsp,
  getStrictCsp,
} from "./security-headers.js";
export { validateBody, validateQuery, validateParams } from "./validation.js";
export { cors } from "./cors.js";
export { requestSizeLimits } from "./request-limits.js";
export { inputSanitization, getSanitizedQuery } from "./input-sanitization.js";
export { pathTraversalPrevention, isSafePath } from "./path-traversal.js";
export {
  hppProtection,
  getCleanedQuery,
  getCleanedBody,
  getCleanedForm,
} from "./parameter-pollution.js";
export { validateContentType, requireJson, requireFormData } from "./content-type.js";
export {
  headerValidation,
  strictHeaderValidation,
  type HeaderValidationOptions,
} from "./header-validation.js";
export {
  staticCache,
  semiStaticCache,
  realtimeCache,
  apiCache,
  healthCache,
  noCache,
  noStore,
  etagCache,
  conditionalGet,
  immutableCache,
} from "./cache.js";
export {
  apiKeyAuth,
  signedRequestAuth,
  optionalAuth,
  requireScope,
  getAuthContext,
  isAuthenticated,
  registerApiKey,
  createSession,
  invalidateSession,
  invalidateAllSessionsForKey,
  generateApiKey,
  hashApiKey,
  validatePassword,
  hashPassword,
  verifyPasswordHash,
  generatePasswordResetToken,
  validatePasswordResetToken,
  consumePasswordResetToken,
  invalidateResetTokensForKey,
  isPasswordExpired,
  getDaysUntilExpiration,
  shouldWarnPasswordExpiration,
  generateSecurePassword,
  getPasswordPolicyDescription,
  resetSuspiciousActivityTracking,
  resetAuthFailureTracking,
  type ApiKey,
  type AuthContext,
  type ApiKeyScope,
  type AuthSession,
  type PasswordPolicy,
  type PasswordValidationResult,
  type PasswordHash,
  type PasswordResetToken,
  type PasswordHistoryEntry,
} from "./authentication.js";

export {
  getDeviceInfo,
  isAccountLocked,
  recordFailedResetAttempt,
  clearFailedResetAttempts,
  getFailedResetAttemptCount,
  cleanupExpiredTokens,
  clearBreachedPasswordCache,
  storePasswordInHistory,
  getPasswordHistory,
  clearPasswordHistory,
  setPasswordPepper,
  _startTokenCleanup,
  _stopTokenCleanup,
  _getPasswordResetTokensMap,
} from "./password-management.js";
export {
  csrfProtection,
  validateCsrf,
  generateCsrfToken,
  generateSessionCsrfToken,
  validateCsrfToken,
  markCsrfTokenUsed,
  revokeCsrfToken,
  getCsrfToken,
} from "./csrf-protection.js";
export {
  ssrfProtection,
  validateUrl,
  safeFetch,
  createMtaFeedAllowList,
  validateMtaFeedUrl,
  type SsrfProtectionOptions,
  type UrlValidationResult,
} from "./ssrf-protection.js";
export {
  hostHeaderProtection,
  validateHostHeader,
  getValidatedHost,
  type HostHeaderProtectionOptions,
  type HostValidationResult,
} from "./host-header-protection.js";
export {
  securityCheckOnStartup,
  auditDependencies,
  generateSecurityReport,
  isPackageSecure,
  getSecurityRecommendations,
  type SecurityReport,
  type Vulnerability,
  type DependencyInfo,
} from "./dependency-security.js";
export {
  generateSriHash,
  validateSriHash,
  generateSriAttributes,
  validateSriAttributes,
  type SriHashAlgorithm,
  type SriHash,
  type SriAttributes,
} from "./subresource-integrity.js";
export {
  requireResourceAccess,
  requireAdmin,
  requireWrite,
  enforceRateLimitTier,
  requireSameOrigin,
  validateDataAccess,
  checkAuthorization,
  requireMfa,
  auditLogAccess,
  type PermissionAction,
  type ResourceType,
  type ResourcePolicy,
  type AuthorizationResult,
} from "./authorization.js";
export {
  requirePermission,
  requireAnyPermission,
  requireAllPermissions,
  requireRole,
  requireRoleLevel,
  requireOwnershipOrAdmin,
  conditionalByRole,
  hasPermission,
  hasAnyPermission,
  hasAllPermissions,
  parsePermission,
  buildPermission,
  getRolePermissions,
  getRoleDefinition,
  getAllRoleDefinitions,
  roleHasPermission,
  isRoleHigher,
  getHighestRole,
  assignRoleToApiKey,
  grantPermissionsToApiKey,
  revokePermissionsFromApiKey,
  getApiKeyPermissions,
  getRbacAuthContext,
  PermissionGroups,
  type RbacAuthContext,
  type RbacOptions,
  type ResourceCategory,
  type PermissionAction,
  type RoleDefinition,
} from "./rbac.js";
export {
  securityLogger,
  securityLogging,
} from "./security-logging.js";
export {
  massAssignmentProtection,
  validateMassAssignment,
  filterAllowedFields,
  removeSensitiveFields,
  PUSH_SUBSCRIPTION_FIELDS,
  TRIP_NOTES_FIELDS,
  CONTEXT_SETTINGS_FIELDS,
  COMMUTE_ANALYZE_FIELDS,
  getSanitizedBody,
} from "./mass-assignment.js";
export {
  openRedirectProtection,
  validateRedirectUrl,
  createSafeRedirect,
  OAUTH_ALLOWED_HOSTNAMES,
  SAFE_REDIRECT_TARGETS,
} from "./open-redirect.js";
export {
  sessionSecurity,
  assessSessionRisk,
  recordSecurityEvent,
  clearSecurityEvents,
  getOrCreateDeviceTrust,
  updateDeviceTrust,
  isDeviceTrusted,
  getDeviceTrustLevel,
  setDeviceTrustLevel,
  removeDeviceTrust,
  parseIpAddress,
  areIpsInSameSubnet,
  calculateIpDistance,
  getIpClass,
  analyzeUserAgent,
  calculateUserAgentSimilarity,
  isLegitimateUserAgentChange,
  detectImpossibleTravel,
  calculateDistance,
  type IpInfo,
  type IpSubnet,
  type UserAgentInfo,
  type GeolocationData,
  type SecurityEvent,
  type SessionRiskAssessment,
  type DeviceTrustInfo,
  type DeviceTrustLevel,
  type SessionSecurityMiddlewareOptions,
} from "./session-security.js";
export {
  configureEncryption,
  encryptToken,
  decryptToken,
  encryptObject,
  decryptObject,
  encryptTokens,
  decryptTokens,
  hashToken,
  verifyTokenHash,
  reencryptToken,
  reencryptTokens,
  rotateEncryptionKey,
  generateMasterKey,
  generateTokenFingerprint,
  isEncryptionConfigured,
  getCurrentKeyVersion,
  validateEncryptedData,
  setupTokenEncryption,
  type EncryptedData,
  type EncryptionConfig,
  type KeyDerivationOptions,
} from "./token-encryption.js";
export {
  configureCookieSigning,
  signCookie,
  verifySignedCookie,
  buildCookieString,
  setSecureCookie,
  getSignedCookie,
  deleteCookie,
  csrfCookie,
  generateCookieCsrfToken,
  getCookieCsrfToken,
  setSessionCookie,
  getSessionCookie,
  clearSessionCookie,
  setRefreshTokenCookie,
  getRefreshTokenCookie,
  clearRefreshTokenCookie,
  validateCookieSecurity,
  cookieSecurityValidator,
  cookieSessionAuth,
  type CookieSecurityOptions,
  type CookieSigningConfig,
  type CsrfCookieOptions,
  type SessionCookieOptions,
} from "./cookie-security.js";
export {
  authRateLimit,
  resetRateLimit,
  getRateLimitStatus,
  banIp,
  unbanIp,
  addTrustedIp,
  removeTrustedIp,
  cleanupRateLimits,
  getRateLimitStats,
  _clearAllRateLimits,
  type AuthRateLimitTier,
  type AuthRateLimitConfig,
  type RateLimitResult,
} from "./auth-rate-limit.js";
export {
  verifyCaptcha,
  hasExceededCaptchaAttempts,
  requireCaptcha,
  conditionalCaptcha,
  setDefaultCaptchaConfig,
  registerCaptchaConfig,
  getCaptchaConfig,
  getCaptchaChallenge,
  clearFailedCaptchaAttempts,
  resetCaptchaTracking,
  getCaptchaStats,
  type CaptchaProvider,
  type CaptchaConfig,
  type CaptchaVerificationResult,
  type CaptchaChallenge,
  type CaptchaTriggerConditions,
} from "./captcha.js";
export {
  notifySecurityEvent,
  createSecurityEvent,
  setNotificationPreferences,
  getNotificationPreferences,
  registerNotificationTemplate,
  getNotificationHistory,
  getNotificationStats,
  clearNotificationRateLimit,
  type SecurityEventType,
  type SecurityEventSeverity,
  type SecurityEvent,
  type NotificationPreferences,
  type NotificationChannel,
  type NotificationDeliveryResult,
  type NotificationTemplate,
} from "./suspicious-activity-notifications.js";
export {
  registerApiKeyWithMetadata,
  updateApiKeyLastUsed,
  getApiKeysForUser,
  listApiKeys,
  getSafeApiKeyResponse,
  canAssignRole,
  canGrantPermissions,
  requireApiKeyOwnershipOrAdmin,
  validateApiKeyCreateRequest,
  logApiKeyOperation,
  type ApiKeyCreateRequest,
  type ApiKeyResponse,
  type ApiKeyListFilters,
} from "./api-key-management.js";
export {
  addAuditEvent,
  getClientIp,
  getUserAgent,
  extractAuthContext,
  queryAuditLog,
  getAuditLogStats,
  getAuditLogForResource,
  getAuditLogForUser,
  getFailedAuthzAttempts,
  getRecentSecurityEvents,
  logAuthorizationSuccess,
  logAuthorizationFailure,
  logApiKeyCreated,
  logApiKeyRevoked,
  logAdminOperation,
  logDataAccess,
  logSecurityEvent,
  exportAuditLogAsJson,
  exportAuditLogAsCsv,
  applyAuditLogRetention,
  clearAuditLog,
  type AuditEvent,
  type AuditEventCategory,
  type AuditEventSeverity,
  type AuditLogFilters,
  type AuditLogStats,
} from "./audit-log.js";
export {
  hasCrlfInjection,
  sanitizeCrlf,
  isSafeRedirectUrl,
  createSafeRedirectUrl,
  httpResponseSplitting,
  protectRedirect,
  type HttpResponseSplittingOptions,
} from "./http-response-splitting.js";
export {
  hasSmugglingPatterns,
  isValidContentLength,
  hasTransferEncodingAbuse,
  hasConflictingLengthHeaders,
  httpRequestSmuggling,
  strictHttpRequestSmuggling,
  type HttpRequestSmugglingOptions,
} from "./http-request-smuggling.js";
export {
  requireAdminWithAudit,
  requireAdminPermission,
  auditAdminOperation,
  getAdminStatus,
  getAdminUsers,
  getAdminUserDetails,
  revokeUserKeys,
  getAuditLogs,
  getAuditStatistics,
  exportAuditLogs,
  getSecurityEvents,
  revokeApiKeyAdmin,
  type SystemStatus,
  type BulkOperationResult,
  type UserSummary,
} from "./admin-operations.js";
export {
  registerResourceType,
  getResourceType,
  checkResourceAuthorization,
  requireResourceAuthorization,
  requireResourceOwnership,
  checkBatchAuthorization,
  filterAuthorizedResources,
  createAuthorizationContext,
  withAuthorizationContext,
  getAuthorizationContext,
  type ResourceAction,
  type ResourceTypeConfig,
  type AuthorizationCheck,
  type BatchAuthorizationResult,
  type OwnerIdResolver,
} from "./enhanced-authorization.js";
export {
  jsonDepthProtection,
  type JsonDepthProtectionOptions,
} from "./json-depth-protection.js";
export {
  responseSizeLimits,
  createStreamResponse,
  createPaginatedResponse,
  estimatePayloadSize,
  type ResponseSizeLimitOptions,
  type PaginatedResponse,
} from "./response-size-limits.js";
export {
  httpMethodRestrictions,
  strictHttpMethodRestrictions,
  isSafeMethod,
  isDangerousMethod,
  isIdempotentMethod,
  getAllowedMethods,
  getBlockedMethods,
  type HttpMethodRestrictionsOptions,
} from "./http-method-restrictions.js";
export {
  checkTimeBasedAccess,
  requireTimeBasedAccess,
  checkLocationAccess,
  requireLocationAccess,
  analyzeAccessBehavior,
  updateAccessPattern,
  analyzeBehavior,
  checkSessionSecurity,
  clearAccessPatterns,
  getAccessPatternStats,
  type TimeBasedAccessRule,
  type LocationAccessRule,
  type BehavioralAnalysis,
  type AccessPattern,
  type SessionSecurityConfig,
} from "./authorization-security.js";
export {
  validateJwt,
  verifyJwt,
  createJwt,
  decodeJwt,
  validateJwtStructure,
  checkTokenReplay,
  cleanupReplayStore,
  type JwtHeader,
  type JwtPayload,
  type DecodedJwt,
  type JwtValidationOptions,
  type JwtValidationResult,
  type JwtVerificationKey,
} from "./jwt-validation.js";
export {
  startSessionCleanup,
  stopSessionCleanup,
  cleanupExpiredSessions,
  getUserSessions,
  getUserSessionCount,
  getDeviceSessionCount,
  registerSession,
  updateSessionActivity,
  terminateSession,
  terminateAllUserSessions,
  terminateAllOtherSessions,
  pinSession,
  unpinSession,
  getSessionStats,
  clearAllSessions,
  type SessionPriority,
  type ConflictResolution,
  type SessionDeviceInfo,
  type SessionGeoInfo,
  type EnhancedSession,
  type ConcurrentSessionConfig,
  type SessionConflictResult,
} from "./concurrent-session-management.js";
export {
  checkPermission,
  checkPermissions,
  checkAllPermissions,
  checkAnyPermission,
  createPermissionOverride,
  removePermissionOverride,
  getUserOverrides,
  emergencyRevokePermission,
  liftEmergencyRevocation,
  getEmergencyRevocations,
  clearEmergencyRevocations,
  invalidateRoleCache,
  invalidateUserCache,
  invalidatePermissionCache,
  clearCache,
  cleanExpiredEntries,
  getCacheStats,
  resetCacheStats,
  getCacheSizeByRole,
  type PermissionCheckResult,
  type PermissionOverride,
  type RbacCacheConfig,
} from "./dynamic-rbac-cache.js";
export {
  generateDeviceFingerprint,
  recordTokenUsage,
  getTokenUsage,
  detectTokenCompromise,
  revokeToken,
  isTokenRevoked,
  unrevokeToken,
  flagSuspectedCompromise,
  unflagSuspectedCompromise,
  clearOldTokenUsage,
  getTokenTrackingStats,
  type DeviceFingerprint,
  type TokenUsageRecord,
  type CompromiseDetectionResult,
  type EnhancedJwtValidationOptions,
  type TokenRevocation,
} from "./enhanced-jwt-security.js";
export {
  logAuditEvent,
  logAuditEventFromContext,
  redactSensitiveData,
  queryAuditLogs,
  getAuditEvent,
  getRelatedEvents,
  getChildEvents,
  getAuditLogStats as getStructuredAuditLogStats,
  generateComplianceReport,
  getRetentionPolicy,
  setRetentionPolicy,
  applyRetentionPolicies,
  clearAuditLogs,
  getCriticalSecurityEvents,
  getRecentFailedAuths,
  detectSecurityIncidents,
  type StructuredAuditEvent,
  type AuditSeverity,
  type AuditCategory,
  type AuditOutcome,
  type AuditEventMetadata,
  type RetentionPolicy,
  type AuditLogStats,
} from "./structured-audit-log.js";
export {
  createEnhancedAuth,
  requirePermissions,
  getEnhancedAuth,
  requiresAdditionalVerification,
  getSecurityIncidents,
  invalidateUserAuthData,
  getUserSecurityStatus,
  type EnhancedAuthConfig,
  type EnhancedAuthResult,
  type AuthSecurityEvent,
} from "./enhanced-authentication.js";
