export { rateLimiter } from "./rate-limiter.js";
export {
  securityHeaders,
  generateCspNonce,
  getDefaultCsp,
  getStrictCsp,
} from "./security-headers.js";
export { validateBody, validateQuery, validateParams } from "./validation.js";
export { cors } from "./cors.js";
export { requestSizeLimits } from "./request-limits.js";
export { inputSanitization, getSanitizedQuery } from "./input-sanitization.js";
export { pathTraversalPrevention, isSafePath } from "./path-traversal.js";
export {
  hppProtection,
  getCleanedQuery,
  getCleanedBody,
  getCleanedForm,
} from "./parameter-pollution.js";
export { validateContentType, requireJson, requireFormData } from "./content-type.js";
export {
  headerValidation,
  strictHeaderValidation,
  type HeaderValidationOptions,
} from "./header-validation.js";
export {
  staticCache,
  semiStaticCache,
  realtimeCache,
  apiCache,
  healthCache,
  noCache,
  noStore,
  etagCache,
  conditionalGet,
  immutableCache,
} from "./cache.js";
export {
  apiKeyAuth,
  signedRequestAuth,
  optionalAuth,
  requireScope,
  getAuthContext,
  isAuthenticated,
  registerApiKey,
  createSession,
  invalidateSession,
  invalidateAllSessionsForKey,
  generateApiKey,
  hashApiKey,
  validatePassword,
  hashPassword,
  verifyPasswordHash,
  storePasswordInHistory,
  generatePasswordResetToken,
  validatePasswordResetToken,
  consumePasswordResetToken,
  invalidateResetTokensForKey,
  isPasswordExpired,
  getDaysUntilExpiration,
  shouldWarnPasswordExpiration,
  generateSecurePassword,
  getPasswordPolicyDescription,
  setPasswordPepper,
  clearBreachedPasswordCache,
  resetSuspiciousActivityTracking,
  resetAuthFailureTracking,
  type ApiKey,
  type AuthContext,
  type ApiKeyScope,
  type AuthSession,
  type PasswordPolicy,
  type PasswordValidationResult,
  type PasswordHash,
  type PasswordResetToken,
  type PasswordHistoryEntry,
} from "./authentication.js";
export {
  csrfProtection,
  validateCsrf,
  generateCsrfToken,
  generateSessionCsrfToken,
  validateCsrfToken,
  markCsrfTokenUsed,
  revokeCsrfToken,
  getCsrfToken,
} from "./csrf-protection.js";
export {
  ssrfProtection,
  validateUrl,
  safeFetch,
  createMtaFeedAllowList,
  validateMtaFeedUrl,
  type SsrfProtectionOptions,
  type UrlValidationResult,
} from "./ssrf-protection.js";
export {
  hostHeaderProtection,
  validateHostHeader,
  getValidatedHost,
  type HostHeaderProtectionOptions,
  type HostValidationResult,
} from "./host-header-protection.js";
export {
  securityCheckOnStartup,
  auditDependencies,
  generateSecurityReport,
  isPackageSecure,
  getSecurityRecommendations,
  type SecurityReport,
  type Vulnerability,
  type DependencyInfo,
} from "./dependency-security.js";
export {
  generateSriHash,
  validateSriHash,
  generateSriAttributes,
  validateSriAttributes,
  type SriHashAlgorithm,
  type SriHash,
  type SriAttributes,
} from "./subresource-integrity.js";
export {
  requireResourceAccess,
  requireAdmin,
  requireWrite,
  enforceRateLimitTier,
  requireSameOrigin,
  validateDataAccess,
  checkAuthorization,
  requireMfa,
  auditLogAccess,
  type PermissionAction,
  type ResourceType,
  type ResourcePolicy,
  type AuthorizationResult,
} from "./authorization.js";
export {
  requirePermission,
  requireAnyPermission,
  requireAllPermissions,
  requireRole,
  requireRoleLevel,
  requireOwnershipOrAdmin,
  conditionalByRole,
  hasPermission,
  hasAnyPermission,
  hasAllPermissions,
  parsePermission,
  buildPermission,
  getRolePermissions,
  getRoleDefinition,
  getAllRoleDefinitions,
  roleHasPermission,
  isRoleHigher,
  getHighestRole,
  assignRoleToApiKey,
  grantPermissionsToApiKey,
  revokePermissionsFromApiKey,
  getApiKeyPermissions,
  getRbacAuthContext,
  PermissionGroups,
  type RbacAuthContext,
  type RbacOptions,
  type ResourceCategory,
  type PermissionAction,
  type RoleDefinition,
} from "./rbac.js";
export {
  securityLogger,
  securityLogging,
  logAuthFailure,
  logAuthzFailure,
  logSuspiciousActivity,
  logSuspiciousRequest,
  logRateLimitExceeded,
} from "./security-logging.js";
export {
  massAssignmentProtection,
  validateMassAssignment,
  filterAllowedFields,
  removeSensitiveFields,
  PUSH_SUBSCRIPTION_FIELDS,
  TRIP_NOTES_FIELDS,
  CONTEXT_SETTINGS_FIELDS,
  COMMUTE_ANALYZE_FIELDS,
  getSanitizedBody,
} from "./mass-assignment.js";
export {
  openRedirectProtection,
  validateRedirectUrl,
  createSafeRedirect,
  OAUTH_ALLOWED_HOSTNAMES,
  SAFE_REDIRECT_TARGETS,
} from "./open-redirect.js";
export {
  sessionSecurity,
  assessSessionRisk,
  recordSecurityEvent,
  clearSecurityEvents,
  getOrCreateDeviceTrust,
  updateDeviceTrust,
  isDeviceTrusted,
  getDeviceTrustLevel,
  setDeviceTrustLevel,
  removeDeviceTrust,
  parseIpAddress,
  areIpsInSameSubnet,
  calculateIpDistance,
  getIpClass,
  analyzeUserAgent,
  calculateUserAgentSimilarity,
  isLegitimateUserAgentChange,
  detectImpossibleTravel,
  calculateDistance,
  type IpInfo,
  type IpSubnet,
  type UserAgentInfo,
  type GeolocationData,
  type SecurityEvent,
  type SessionRiskAssessment,
  type DeviceTrustInfo,
  type DeviceTrustLevel,
  type SessionSecurityMiddlewareOptions,
} from "./session-security.js";
export {
  configureEncryption,
  encryptToken,
  decryptToken,
  encryptObject,
  decryptObject,
  encryptTokens,
  decryptTokens,
  hashToken,
  verifyTokenHash,
  reencryptToken,
  reencryptTokens,
  rotateEncryptionKey,
  generateMasterKey,
  generateTokenFingerprint,
  isEncryptionConfigured,
  getCurrentKeyVersion,
  validateEncryptedData,
  setupTokenEncryption,
  type EncryptedData,
  type EncryptionConfig,
  type KeyDerivationOptions,
} from "./token-encryption.js";
export {
  configureCookieSigning,
  signCookie,
  verifySignedCookie,
  buildCookieString,
  setSecureCookie,
  getSignedCookie,
  deleteCookie,
  csrfCookie,
  generateCsrfToken,
  getCsrfToken,
  setSessionCookie,
  getSessionCookie,
  clearSessionCookie,
  setRefreshTokenCookie,
  getRefreshTokenCookie,
  clearRefreshTokenCookie,
  validateCookieSecurity,
  cookieSecurityValidator,
  cookieSessionAuth,
  type CookieSecurityOptions,
  type CookieSigningConfig,
  type CsrfCookieOptions,
  type SessionCookieOptions,
} from "./cookie-security.js";
export {
  authRateLimit,
  resetRateLimit,
  getRateLimitStatus,
  banIp,
  unbanIp,
  addTrustedIp,
  removeTrustedIp,
  cleanupRateLimits,
  getRateLimitStats,
  type AuthRateLimitTier,
  type AuthRateLimitConfig,
  type RateLimitResult,
} from "./auth-rate-limit.js";
export {
  verifyCaptcha,
  hasExceededCaptchaAttempts,
  requireCaptcha,
  conditionalCaptcha,
  setDefaultCaptchaConfig,
  registerCaptchaConfig,
  getCaptchaConfig,
  getCaptchaChallenge,
  clearFailedCaptchaAttempts,
  resetCaptchaTracking,
  getCaptchaStats,
  type CaptchaProvider,
  type CaptchaConfig,
  type CaptchaVerificationResult,
  type CaptchaChallenge,
  type CaptchaTriggerConditions,
} from "./captcha.js";
export {
  notifySecurityEvent,
  createSecurityEvent,
  setNotificationPreferences,
  getNotificationPreferences,
  registerNotificationTemplate,
  getNotificationHistory,
  getNotificationStats,
  clearNotificationRateLimit,
  type SecurityEventType,
  type SecurityEventSeverity,
  type SecurityEvent,
  type NotificationPreferences,
  type NotificationChannel,
  type NotificationDeliveryResult,
  type NotificationTemplate,
} from "./suspicious-activity-notifications.js";
export {
  registerApiKeyWithMetadata,
  updateApiKeyLastUsed,
  getApiKeysForUser,
  listApiKeys,
  getSafeApiKeyResponse,
  canAssignRole,
  canGrantPermissions,
  requireApiKeyOwnershipOrAdmin,
  validateApiKeyCreateRequest,
  logApiKeyOperation,
  type ApiKeyCreateRequest,
  type ApiKeyResponse,
  type ApiKeyListFilters,
} from "./api-key-management.js";
export {
  addAuditEvent,
  getClientIp,
  getUserAgent,
  extractAuthContext,
  queryAuditLog,
  getAuditLogStats,
  getAuditLogForResource,
  getAuditLogForUser,
  getFailedAuthzAttempts,
  getRecentSecurityEvents,
  logAuthorizationSuccess,
  logAuthorizationFailure,
  logApiKeyCreated,
  logApiKeyRevoked,
  logAdminOperation,
  logDataAccess,
  logSecurityEvent,
  exportAuditLogAsJson,
  exportAuditLogAsCsv,
  applyAuditLogRetention,
  clearAuditLog,
  type AuditEvent,
  type AuditEventCategory,
  type AuditEventSeverity,
  type AuditLogFilters,
  type AuditLogStats,
} from "./audit-log.js";
export {
  requireAdminWithAudit,
  requireAdminPermission,
  auditAdminOperation,
  getAdminStatus,
  getAdminUsers,
  getAdminUserDetails,
  revokeUserKeys,
  getAuditLogs,
  getAuditStatistics,
  exportAuditLogs,
  getSecurityEvents,
  revokeApiKeyAdmin,
  type SystemStatus,
  type BulkOperationResult,
  type UserSummary,
} from "./admin-operations.js";
export {
  registerResourceType,
  getResourceType,
  checkResourceAuthorization,
  requireResourceAuthorization,
  requireResourceOwnership,
  checkBatchAuthorization,
  filterAuthorizedResources,
  createAuthorizationContext,
  withAuthorizationContext,
  getAuthorizationContext,
  type ResourceAction,
  type ResourceTypeConfig,
  type AuthorizationCheck,
  type BatchAuthorizationResult,
  type OwnerIdResolver,
} from "./enhanced-authorization.js";
