/**
 * MfaVerifyScreen - Multi-factor authentication verification screen.
 *
 * Used during login flow to verify user's TOTP code.
 */

import { useState } from "react";
import { useNavigate } from "react-router-dom";
import Screen from "../components/layout/Screen";
import { useMFA } from "../hooks/useMFA";

export default function MfaVerifyScreen() {
  const { isLoading, error, verifyMfa } = useMFA();
  const navigate = useNavigate();
  const [verificationCode, setVerificationCode] = useState<string>("");
  const [useBackupCode, setUseBackupCode] = useState<boolean>(false);

  const handleVerifyCode = async (): Promise<void> => {
    if (!verificationCode) {
      return;
    }

    const result = await verifyMfa(verificationCode);
    if (result?.success) {
      // Navigate to home or originally requested page
      navigate("/", { replace: true });
    }
  };

  const handleResendCode = (): void => {
    // For TOTP, codes are generated by the app, so this is more of a help link
    // Could open a modal with instructions or link to support
    window.open("https://support.google.com/accounts/answer/1066447", "_blank");
  };

  const handleLogout = (): void => {
    // Clear session and return to login
    document.cookie = "session_id=; Path=/; SameSite=Lax; Secure; HttpOnly; Max-Age=0";
    navigate("/login", { replace: true });
  };

  const inputLength = useBackupCode ? 8 : 6;
  const inputPattern = useBackupCode ? "[a-f0-9]*" : "[0-9]*";
  const placeholder = useBackupCode ? "aaaaaaaa" : "000000";

  return (
    <Screen>
      <div className="max-w-md mx-auto px-4 py-8">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-mta-primary/10 flex items-center justify-center">
            <svg
              className="w-8 h-8 text-mta-primary"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"
              />
            </svg>
          </div>
          <h1 className="text-2xl font-bold text-text-primary dark:text-dark-text-primary mb-2">
            Two-Factor Authentication
          </h1>
          <p className="text-text-secondary dark:text-dark-text-secondary">
            Enter the verification code from your authenticator app
          </p>
        </div>

        {/* Error Message */}
        {error && (
          <div
            role="alert"
            className="mb-4 p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg"
          >
            <p className="text-sm text-red-800 dark:text-red-200">{error}</p>
          </div>
        )}

        {/* Verification Form */}
        <div className="space-y-6">
          {/* Code Type Toggle */}
          <div className="flex gap-2 p-1 bg-background-secondary dark:bg-dark-background-secondary rounded-lg">
            <button
              type="button"
              onClick={() => {
                setUseBackupCode(false);
                setVerificationCode("");
              }}
              className={
                !useBackupCode
                  ? "flex-1 px-4 py-2 rounded-md text-sm font-medium transition-colors bg-white dark:bg-gray-800 text-text-primary dark:text-dark-text-primary shadow-sm"
                  : "flex-1 px-4 py-2 rounded-md text-sm font-medium transition-colors text-text-secondary dark:text-dark-text-secondary hover:text-text-primary"
              }
            >
              Authenticator Code
            </button>
            <button
              type="button"
              onClick={() => {
                setUseBackupCode(true);
                setVerificationCode("");
              }}
              className={
                useBackupCode
                  ? "flex-1 px-4 py-2 rounded-md text-sm font-medium transition-colors bg-white dark:bg-gray-800 text-text-primary dark:text-dark-text-primary shadow-sm"
                  : "flex-1 px-4 py-2 rounded-md text-sm font-medium transition-colors text-text-secondary dark:text-dark-text-secondary hover:text-text-primary"
              }
            >
              Backup Code
            </button>
          </div>

          {/* Code Input */}
          <div>
            <label
              htmlFor="verification-code"
              className="block text-sm font-medium text-text-primary dark:text-dark-text-primary mb-2"
            >
              {useBackupCode ? "Backup Code" : "Authentication Code"}
            </label>
            <input
              id="verification-code"
              type="text"
              inputMode={useBackupCode ? "text" : "numeric"}
              pattern={inputPattern}
              maxLength={inputLength}
              value={verificationCode}
              onChange={(e) => {
                const value = useBackupCode
                  ? e.target.value
                      .toLowerCase()
                      .replace(/[^a-f0-9]/g, "")
                      .slice(0, inputLength)
                  : e.target.value.replace(/\D/g, "").slice(0, inputLength);
                setVerificationCode(value);
              }}
              placeholder={placeholder}
              className={[
                "w-full px-4 py-3 text-center text-2xl tracking-widest",
                "border border-gray-300 dark:border-gray-600 rounded-lg",
                "bg-white dark:bg-gray-800",
                "text-text-primary dark:text-dark-text-primary",
                "focus:outline-none focus:ring-2 focus:ring-mta-primary focus:border-transparent",
                "disabled:opacity-50 disabled:cursor-not-allowed",
              ].join(" ")}
              disabled={isLoading}
              autoFocus
              onKeyDown={(e) => {
                if (e.key === "Enter" && verificationCode.length === inputLength) {
                  void handleVerifyCode();
                }
              }}
            />
            <p className="mt-2 text-xs text-text-secondary dark:text-dark-text-secondary">
              {useBackupCode
                ? "Enter one of your 8-character backup codes"
                : "Enter the 6-digit code from your authenticator app"}
            </p>
          </div>

          {/* Verify Button */}
          <button
            type="button"
            onClick={() => {
              void handleVerifyCode();
            }}
            disabled={verificationCode.length !== inputLength || isLoading}
            className={[
              "w-full px-4 py-3 bg-mta-primary hover:bg-mta-primary/90 text-white rounded-lg font-medium",
              "transition-colors focus:outline-none focus:ring-2 focus:ring-mta-primary focus:ring-offset-2",
              "disabled:opacity-50 disabled:cursor-not-allowed",
            ].join(" ")}
          >
            {isLoading ? "Verifying..." : "Verify"}
          </button>

          {/* Help Links */}
          <div className="flex justify-between items-center text-sm">
            <button
              type="button"
              onClick={handleResendCode}
              className="text-mta-primary hover:underline"
            >
              Need help?
            </button>
            <button
              type="button"
              onClick={handleLogout}
              className="text-text-secondary dark:text-dark-text-secondary hover:text-text-primary"
            >
              Cancel
            </button>
          </div>

          {/* Info Box */}
          <div className="p-4 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg">
            <p className="text-sm text-blue-800 dark:text-blue-200">
              <strong>Tip:</strong> The verification code changes every 30 seconds. If the code
              doesn't work, wait for a new one and try again.
            </p>
          </div>
        </div>
      </div>
    </Screen>
  );
}
